#!/bin/bash

set -e

mute() { $@ >/dev/null 2>&1; }
die() { echo $@ ; exit 1; }

# If the URI is google_metadata:// then fetch the details from metadata service
#
if [ "${PRITUNL_MONGODB_URI%%:*}" == "metadata_google" ]; then
  PRITUNL_MONGODB_URI=$(curl -sSL -H 'Metadata-Flavor: Google' ${PRITUNL_MONGODB_URI/metadata_google/http} | base64 -d)
fi

# If no MongoDB then bail out
#
if [ -z "$PRITUNL_MONGODB_URI" ]; then
  echo No MongoDB defined, aborting
  exit 1
fi

# Make sure /dev/net is configured correctly
#
[ -d /dev/net ] ||
    mkdir -p /dev/net

[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200

# Make sure our tmp files are written to tmpfs and not overlay
#
mount -t tmpfs -o size=${PRITUNL_TMPFS_SIZE:-512M} tmpfs /tmp

# Simplify disabling web interface by binding to localhost rather than make user understand how to do that
#
[ -n "$NO_WEB" ] && PRITUNL_BIND_ADDR=127.0.0.1

# Define where our state files are
#
PRITUNL_TMP_PATH=${PRITUNL_TMP_PATH:-/tmp/pritunl}
PRITUNL_PERSIST_PATH=${PRITUNL_PERSIST_PATH:-/data/pritunl}

PRITUNL_LOG_FILE=${PRITUNL_LOG_FILE:-${PRITUNL_TMP_PATH}/pritunl.log}
PRITUNL_PID_FILE=${PRITUNL_PID_FILE:-${PRITUNL_TMP_PATH}/pritunl.pid}
PRITUNL_SETUP_KEY_FILE=${PRITUNL_SETUP_KEY_FILE:-${PRITUNL_PERSIST_PATH}/pritunl.setup_key}
PRITUNL_UUID_FILE=${PRITUNL_UUID_FILE:-${PRITUNL_PERSIST_PATH}/pritunl.uuid}
PRITUNL_SERVER_KEY_FILE=${PRITUNL_SERVER_KEY_FILE:-${PRITUNL_PERSIST_PATH}/server.key}
PRITUNL_SERVER_CRT_FILE=${PRITUNL_SERVER_CRT_FILE:-${PRITUNL_PERSIST_PATH}/server.crt}
PRITUNL_CONF_FILE=/etc/pritunl.conf

test_file() {
  [ -z "$1" ] && die test_file called without any params
  mute mkdir -p $(dirname ${1})
  touch ${1} || die Cant touch ${1}
  if [ -n "$2" ]; then eval $2 $1; fi
}

mute mkdir -p ${PRITUNL_TMP_PATH}
mute mkdir -p ${PRITUNL_PERSIST_PATH}

test_file ${PRITUNL_LOG_FILE}
test_file ${PRITUNL_PID_FILE} rm
test_file ${PRITUNL_CONF_FILE}

cat << EOF > ${PRITUNL_CONF_FILE}
{
    "log_path": "${PRITUNL_LOG_FILE}",
    "setup_key_path": "${PRITUNL_SETUP_KEY_FILE}",
    "uuid_path": "${PRITUNL_UUID_FILE}",

    "var_run_path": "${PRITUNL_TMP_PATH}",
    "server_key_path": "${PRITUNL_SERVER_KEY_FILE}",
    "server_cert_path": "${PRITUNL_SERVER_CRT_FILE}",
    "temp_path": "${PRITUNL_TMP_PATH}",

    "debug": ${PRITUNL_DEBUG:-false},
    "port": ${PRITUNL_PORT:-9700},
    "bind_addr": "${PRITUNL_BIND_ADDR:-0.0.0.0}",
    "static_cache": ${PRITUNL_STATIC_CACHE:-true},
    "mongodb_uri": "${PRITUNL_MONGODB_URI}",
    "local_address_interface": "${PRITUNL_LOCAL_ADDRESS_INTERFACE:-auto}"
}
EOF

stop_pritunl() {
  # Get the running pid (once), then proceed to kill it and wait for termination
  #
  pritunl_pid=$(cat ${PRITUNL_PID_FILE})
  echo Killing PriTunl pid=${pritunl_pid} cmdline=$(cat /proc/${pritunl_pid}/cmdline | tr '\0' ' ')
  kill ${pritunl_pid}

  echo waiting for Server to exit
  while [ -f /proc/${pritunl_pid}/stat ]; do
    echo -n .
    sleep 1
  done

  # Wait an extra 5 seconds for logs to update on DB
  sleep 5
  exit 1
}

# Setup our kill handler
#
trap stop_pritunl TERM INT

# Launch the service as a daemon
#
/usr/bin/pritunl start --pidfile=${PRITUNL_PID_FILE} --conf=${PRITUNL_CONF_FILE} --daemon

# Wait 5 seconds for process to start then get its PID
#
sleep 5
pritunl_pid=$(cat ${PRITUNL_PID_FILE})
echo PriTunl Started pid=${pritunl_pid} cmdline=$(cat /proc/${pritunl_pid}/cmdline | tr '\0' ' ')

# If user gave us a command transfer control to it (breaks SIGTERM handler)
#
[ "$1" ] && exec "$@"

# Otherwise tail the pritunl logs to stdout (without waiting on child, otherwise SIGTERM handler doesnt work)
#
/usr/bin/pritunl logs --tail &

# prevent shell from exiting while the pritunl process is running
# We can't sleep 60 because that prevents the trap from being handled, so sleep 1 reduces cycle
#
while [ -f /proc/${pritunl_pid}/stat ]; do sleep 1; done
exit 0
